### ISSUE TITLE
BUG:  Can no longer build RTFaceLogin

### ISSUE THREAD

**Issue by JackMostow** [RoboTutorLLC/RTFace_Login#30]
Madelein can no longer build FaceLogin:

I am getting this build error on my end with FaceLogin:
A problem occurred evaluating project ':app'.
> No signature of method: build_9g1a2ena16yjqnzbe1vhscb5z.android() is applicable for argument types: (build_9g1a2ena16yjqnzbe1vhscb5z$_run_closure1) values: [build_9g1a2ena16yjqnzbe1vhscb5z$_run_closure1@5466680c]

I experienced it right after updating Android Studio (It is not because of the update since RoboTutor still builds perfectly fine). I tried deleting and re-cloning the repo but had the same issue. Dr. Google also has not been of any help.

**Comment by JackMostow** [comment]
Dependency changed:  need to change Android.support to AndroidX using Migrate in Android Studio

**Comment by JackMostow** [comment]
Madelein will try deleting and recloning.

**Comment by madeleinvillegas** [comment]
So the problem still persists. It is because of the signingConfigs, the keystore file is not read/parsed properly. 

Quick/temporary fix: Commented out all the lines in build.gradle that have to do with the signingConfig and used the Generate Signed APK option to attach a keystore to create an apk

**Comment by JackMostow** [comment]
See progress at [2022-12-21 meet with Bhuvan and Bhargav](https://docs.google.com/document/d/1GJprHeb1s4YVM4ud6vTQiloQ76JnsvwhUlYBaT8N-t4/edit#heading=h.tg4o67x9rl5l).

**Comment by madeleinvillegas** [comment]
Just create an automatically generated apk by committing to a branch
