### ISSUE TITLE
BUG Swahili 1.8.2.1 Shows picture of bat mislabeled as PUNDA (ZEBRA)

### ISSUE THREAD

**Issue by JackMostow** [RoboTutorLLC/RTFace_Login#40]
Posing as a new user, I picked a picture but FaceLogin is displaying a picture of a bat labelled as PUNDA (ZEBRA):

[Screenshot_20221231-182108.png](https://drive.google.com/file/d/1_EizfCx8MxoNLLSWqiV3zuVc6Z7gOEn9/view?usp=share_link)

Moreover, I don't think I picked either animal.  I'm sure I didn't pick BAT.  It used to be the first one listed.

Later (after picking a different animal), I saw duplicate animals:

[Screenshot_20221231-183052.png](https://drive.google.com/file/d/1_QZqzHNw9MTnwCzeeYFaPRGoaBjfvZ-v/view?usp=share_link)

Suggestions for debugging:

1. #23 to log states
2. Try replacing the older code for getImageOrder with the commented-out simple query at ll. 226ff of [DataHelper.java](https://github.com/RoboTutorLLC/RTFace_Login/blob/6d201b6dbd6c6855c8dbaf5c7df9922aeede8bff/app/src/main/java/com/example/iris/login1/DataHelper.java)

**Comment by rohankulkz** [comment]
Hi Professor,

I also had that problem a few weeks back, but I thought I had resolved it.
I will take a look at the most recent branch and see what I can do.
Strangely enough, when I had that problem, it was only present in the
English version.

Thanks,
Rohan

**Comment by JackMostow** [comment]
Dear Rohan,

I think the latest branch is
https://github.com/RoboTutorLLC/RTFace_Login/tree/2022-12-27-Madelein-Swahili-Github-Actions,
at least that's the apk I've been trying, but now we use GitHub
actions rather than Travis to generate apks, so I'm not absolutely sure.

It would be great if you can implement my 2 suggestions in the issue.  It
would be even greater if they lead to success ;-).
Madelein may already be working on logging state changes, but there's a
one-line version that should be trivial to implement (famous last words ;-).

Thanks, and Happy New Year!  (you too, Madelein!)  - Jack

**Comment by JackMostow** [comment]
Rohan fixed
