### ISSUE TITLE
CRASH RTFaceLogin 1.8.2.2 but which one?  can't tell from CRASH log

### ISSUE THREAD

**Issue by RTBagamoyo** [RoboTutorLLC/RTFace_Login#63]
There are dozens of CRASH logs for 1.8.2.2 but which version of it?  Which crashes remain to fix?

Including build timestamp in log filenames should eliminate this ambiguity in future.

**Comment by JackMostow** [comment]
Modify FaceLogin to include version identifier in (crash) log filenames and CoLab scripts to parse them.
See details in [2023-07-20 Rishideep Meeting 21 Notes](https://docs.google.com/document/d/1uKbQzZVPZTnEi33BgmTSlhUFENmRipzYfmcHnBYNNKE/edit).
